[package]
name = "day-16"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
aoc-cli.workspace = true
itertools = "0.14.0"
pathfinding = "4.13.1"
regex = "1.11.1"
